/**
 * Trạng thái phiên đặt bàn (reservations.status)
 */

const RESERVATION_STATUS = {
  PENDING: "pending",
  CONFIRMED: "confirmed",
  PRE_ORDERED: "pre-ordered",
  WAITING_PAYMENT: "waiting_payment",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
};

const ACTIVE_RESERVATION_STATUSES = [
  RESERVATION_STATUS.CONFIRMED,
  RESERVATION_STATUS.PRE_ORDERED,
  RESERVATION_STATUS.WAITING_PAYMENT,
];

const CHECK_IN_RESERVATION_STATUSES = [
  RESERVATION_STATUS.CONFIRMED,
  RESERVATION_STATUS.PENDING,
];

const ACTIVE_SESSION_STATUSES = [
  RESERVATION_STATUS.PRE_ORDERED,
  RESERVATION_STATUS.WAITING_PAYMENT,
];

const CANCELABLE_RESERVATION_STATUSES = [
  RESERVATION_STATUS.PENDING,
  RESERVATION_STATUS.CONFIRMED,
];

function activeReservationStatusWhere() {
  const { Op } = require("sequelize");
  return { [Op.in]: ACTIVE_RESERVATION_STATUSES };
}

module.exports = {
  RESERVATION_STATUS,
  ACTIVE_RESERVATION_STATUSES,
  CHECK_IN_RESERVATION_STATUSES,
  ACTIVE_SESSION_STATUSES,
  CANCELABLE_RESERVATION_STATUSES,
  activeReservationStatusWhere,
};
